export const options = [
    { value: "red", label: "Czerwony" },
    { value: "green", label: "Zielony" },
    { value: "pink", label: "Różowy" },
    { value: "purple", label: "Fioletowy" },
    { value: "orange", label: "Pomarańczowy" },
    { value: "cyan", label: "Błękitny" },
    { value: "magenta", label: "Purpurowy" },
    { value: "yellow", label: "Żółty" },
    { value: "blue", label: "Niebieski" },
    { value: "brown", label: "Brązowy" },
    { value: "black", label: "Czarny" },
    { value: "gray", label: "Szary" },
    { value: "silver", label: "Srebrny" },
    { value: "gold", label: "Złoty" },
    { value: "violet", label: "Fiolet" },
    { value: "maroon", label: "Kasztanowy" },
    { value: "olive", label: "Oliwkowy" },
    { value: "navy", label: "Granatowy" },
    { value: "turquoise", label: "Turkusowy" },
    { value: "white", label: "Biały" },
];

export const tags = [
    { name: "uroda", value: "beauty" },
    { name: "moda", value: "fashion" },
    { name: "jedzenie", value: "food" },
    { name: "podróże", value: "travel" },
    { name: "sport", value: "sport" },
];
